name: rationalowl_flutter
description: "Flutter plugin for RationalOwl, a realtime mobile messaging service"
homepage: https://www.rationalowl.com
repository: https://github.com/RationalOwl/rationalowl_flutter
version: 1.0.0

false_secrets:
  - example/**

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  plugin:
    platforms:
      android:
        package: com.rationalowl.rationalowl_flutter
        pluginClass: FlutterRationalOwlPlugin
      ios:
        pluginClass: FlutterRationalOwlPlugin
