name: rationalowl_flutter
description: "Flutter plugin for RationalOwl, a realtime mobile messaging service"
version: 1.1.1
homepage: https://www.rationalowl.com
repository: https://github.com/RationalOwl/rationalowl_flutter

false_secrets:
  - example/**

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  plugin:
    platforms:
      android:
        package: com.rationalowl.rationalowl_flutter
        pluginClass: FlutterRationalOwlPlugin
      ios:
        pluginClass: FlutterRationalOwlPlugin
